# Generated by Django 4.2.16 on 2024-09-08 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_comments_count_alter_user_posts_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="posts_count",
        ),
        migrations.AddField(
            model_name="user",
            name="publications_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Each time a Publication is created, this field is actuallized. Check signal 'publications.update_user_publications_count'",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="comments_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Each time a PublicationComment is created, this field is actuallized. Check signal 'publications.update_user_comments_count'",
            ),
        ),
    ]
