# Generated by Django 4.2.16 on 2024-09-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_user_posts_count_user_publications_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="updated",
        ),
    ]
