repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: debug-statements
  - repo: https://github.com/ambv/black
    rev: 24.8.0
    hooks:
      - id: black # to disable black in a section code, use: # fmt: off, and then: # fmt: on
        language_version: python3.12
        exclude: migrations|manage.py
        args: [--line-length=120, --exclude=/(\.git|\.venv|migrations)/]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        exclude: migrations/
        args: [--lbt=1, --settings=.isort.cfg, --profile=black]
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
