# Generated by Django 4.2.16 on 2024-09-08 05:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="PublicationComment",
        ),
    ]
