# Generated by Django 4.2.16 on 2024-09-08 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0002_rename_comment_publicationcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicationcomment",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="publications.publication",
            ),
        ),
    ]
