# Generated by Django 4.2.16 on 2024-09-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0003_alter_publicationcomment_publication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="publicationcomment",
            name="updated",
        ),
    ]
